<?php
ob_start();
?>
<section class="page-head compact"><div><a class="back-link" href="/reservations">← Retour</a><span class="eyebrow">PLANNING / NOUVELLE RESERVATION</span><h1>Réserver une <span class="gradient-text">salle</span></h1><p>Choisissez un espace et définissez le créneau souhaité.</p></div></section>

<?php if ($serviceError): ?><div class="alert alert-danger">! <?= htmlspecialchars((string) $serviceError, ENT_QUOTES, 'UTF-8') ?></div><?php endif; ?>

<div class="form-shell card"><form method="post" action="/reservations" novalidate><input type="hidden" name="_csrf_token" value="<?= htmlspecialchars($csrfToken, ENT_QUOTES, 'UTF-8') ?>"><div class="form-grid">
    <div class="form-group full"><label for="salle_id">Salle</label><select class="form-control <?= isset($errors['salle_id']) ? 'input-error' : '' ?>" id="salle_id" name="salle_id" required><option value="">Sélectionner une salle active</option><?php foreach ($salles as $salle): ?><option value="<?= (int) $salle->id ?>" <?= (string) ($old['salle_id'] ?? '') === (string) $salle->id ? 'selected' : '' ?>><?= htmlspecialchars($salle->nom, ENT_QUOTES, 'UTF-8') ?> · <?= htmlspecialchars($salle->batiment, ENT_QUOTES, 'UTF-8') ?> · <?= (int) $salle->capacite ?> places</option><?php endforeach; ?></select><?php if (isset($errors['salle_id'])): ?><span class="field-error"><?= htmlspecialchars($errors['salle_id'], ENT_QUOTES, 'UTF-8') ?></span><?php endif; ?></div>
    <div class="form-group"><label for="responsable">Responsable</label><input class="form-control <?= isset($errors['responsable']) ? 'input-error' : '' ?>" id="responsable" name="responsable" value="<?= htmlspecialchars((string) ($old['responsable'] ?? ''), ENT_QUOTES, 'UTF-8') ?>" placeholder="Nom complet" required><?php if (isset($errors['responsable'])): ?><span class="field-error"><?= htmlspecialchars($errors['responsable'], ENT_QUOTES, 'UTF-8') ?></span><?php endif; ?></div>
    <div class="form-group"><label for="email">Adresse email</label><input type="email" class="form-control <?= isset($errors['email']) ? 'input-error' : '' ?>" id="email" name="email" value="<?= htmlspecialchars((string) ($old['email'] ?? ''), ENT_QUOTES, 'UTF-8') ?>" placeholder="nom@universite.sn" required><?php if (isset($errors['email'])): ?><span class="field-error"><?= htmlspecialchars($errors['email'], ENT_QUOTES, 'UTF-8') ?></span><?php endif; ?></div>
    <div class="form-group full"><label for="motif">Motif</label><textarea class="form-control <?= isset($errors['motif']) ? 'input-error' : '' ?>" id="motif" name="motif" rows="3" minlength="5" maxlength="255" placeholder="Motif de la réservation" required><?= htmlspecialchars((string) ($old['motif'] ?? ''), ENT_QUOTES, 'UTF-8') ?></textarea><?php if (isset($errors['motif'])): ?><span class="field-error"><?= htmlspecialchars($errors['motif'], ENT_QUOTES, 'UTF-8') ?></span><?php endif; ?></div>
    <div class="form-group"><label for="date_debut">Début</label><input type="datetime-local" class="form-control <?= isset($errors['date_debut']) ? 'input-error' : '' ?>" id="date_debut" name="date_debut" value="<?= htmlspecialchars(str_replace(' ', 'T', substr((string) ($old['date_debut'] ?? ''), 0, 16)), ENT_QUOTES, 'UTF-8') ?>" required><?php if (isset($errors['date_debut'])): ?><span class="field-error"><?= htmlspecialchars($errors['date_debut'], ENT_QUOTES, 'UTF-8') ?></span><?php endif; ?></div>
    <div class="form-group"><label for="date_fin">Fin</label><input type="datetime-local" class="form-control <?= isset($errors['date_fin']) ? 'input-error' : '' ?>" id="date_fin" name="date_fin" value="<?= htmlspecialchars(str_replace(' ', 'T', substr((string) ($old['date_fin'] ?? ''), 0, 16)), ENT_QUOTES, 'UTF-8') ?>" required><?php if (isset($errors['date_fin'])): ?><span class="field-error"><?= htmlspecialchars($errors['date_fin'], ENT_QUOTES, 'UTF-8') ?></span><?php endif; ?></div>
</div><div class="form-hint">ⓘ La réservation doit commencer dans le futur et ne peut pas dépasser 4 heures.</div><div class="form-actions"><a class="btn btn-secondary" href="/reservations">Annuler</a><button class="btn btn-primary" type="submit">Confirmer la réservation →</button></div></form></div>
<?php
$content = ob_get_clean();
require __DIR__ . '/../layout/base.php';
